SELECT * from mytable limit 20;
-- What is the total revenue generated by male vs. female customers
SELECT gender, SUM(`purchase_amount`) as revenue
FROM mytable
GROUP BY gender;
--Which customers used a discount but still spent more than the average purchase 
SELECT `customer_id`, `purchase_amount`
FROM mytable
WHERE `discount_applied` = 'Yes' and `purchase_amount`>= (select AVG(`purchase_amount`) from mytable);
--which are the top 5 products with highest average review_rating
SELECT `item_purchased`,ROUND(AVG(`review_rating`),2) as "Average Product Rating"
FROM mytable
GROUP BY `item_purchased`
ORDER BY AVG(`review_rating`) DESC
LIMIT 5;
--compare the average purchase amounts between standard and express shipping methods
SELECT `shipping_type`, ROUND(AVG(`purchase_amount`),2) as "Average Purchase Amount"
FROM mytable
WHERE `shipping_type` IN ('Standard', 'Express')
GROUP BY `shipping_type`;
--do subscribed customers spend more?compare average spend and total revenue between subscribed and non-subscribed customers
SELECT `subscription_status`, 
COUNT(`customer_id`) as total_customers,
ROUND(AVG(`purchase_amount`),2) as avg_spend,
ROUND(SUM(`purchase_amount`),2) as total_revenue
FROM mytable
GROUP BY `subscription_status`
ORDER BY total_revenue, avg_spend DESC;
--which 5 products have the highest percentage of purchase with discounts applied
SELECT `item_purchased`,
ROUND(SUM(CASE WHEN `discount_applied` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) as discount_rate
FROM mytable
GROUP BY `item_purchased`
ORDER BY discount_rate DESC
LIMIT 5;
--segment customers into new,returning and loyal based on their total number of previous_purchases and show the count of each segment
WITH customer_type AS (
    SELECT `customer_id`, `previous_purchases`,
    CASE 
        WHEN `previous_purchases` = 1 THEN 'New'
        WHEN `previous_purchases` BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM mytable
)
SELECT customer_segment, COUNT(*) as segment_count
FROM customer_type
GROUP BY customer_segment;
--what are the top 3 most purchased products within each category
WITH item_counts as (
    SELECT `category`, `item_purchased`,
    COUNT(`customer_id`) as total_orders,
    ROW_NUMBER() OVER (PARTITION BY `category` ORDER BY COUNT(`customer_id`) DESC) as item_rank
    FROM mytable
    GROUP BY `category`, `item_purchased`
)
SELECT item_rank, `category`, `item_purchased`, total_orders
FROM item_counts
WHERE item_rank <= 3;
--are customers who are repeat buyers (more than 5 purchases) also lokely to subscribe
SELECT `subscription_status`,
COUNT(`customer_id`) as repeat_buyers
FROM mytable
WHERE `previous_purchases` > 5
GROUP BY `subscription_status`;
--what is the revenue contribution from each age group?
SELECT age_group,
ROUND(SUM(`purchase_amount`),2) as total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;